metrics:
  enabled: true
  image: 
  imageTag:
  securityContext:
    runAsUser: 0
  annotations: {}
  pushMode: true
  pushGateway: http://prometheus-server:9091
  pushMetricCron: "* * * * *"
  fluentbit:
    enabled: true
    configMap:
      name: fluent-bit-config  # Name of the ConfigMap to be mounted
      mountPath: /fluent-bit/etc
    logs:
      vds_server:
        enabled: true
        path: "/opt/radiantone/vds/vds_server/logs/vds_server.log"
        index: vds_server.log
      vds_server_access:
        enabled: true
        path: "/opt/radiantone/vds/vds_server/logs/vds_server_access.csv"
        index: vds_server_access.log
        parse:
          keys: "LOGID,LOGDATE,LOGTIME,LOGTYPE,SERVERID,SERVERPORT,SESSIONID,MSGID,CLIENTIP,BINDDN,BINDUSER,CONNNB,OPNB,OPCODE,OPNAME,BASEDN,ATTRIBUTES,SCOPE,FILTER,SIZELIMIT,TIMELIMIT,LDAPCONTROLS,CHANGES,RESULTCODE,ERRORMESSAGE,MATCHEDDN,NBENTRIES,ETIME"
          types: "LOGID:integer,LOGDATE:string,LOGTIME:string,LOGTYPE:integer,SERVERID:string,SERVERPORT:integer,SESSIONID:integer,MSGID:integer,CLIENTIP:string,BINDDN:string,BINDUSER:string,CONNNB:integer,OPNB:integer,OPCODE:integer,OPNAME:string,BASEDN:string,ATTRIBUTES:string,SCOPE:string,FILTER:string,SIZELIMIT:integer,TIMELIMIT:integer,LDAPCONTROLS:string,CHANGES:string,RESULTCODE:integer,ERRORMESSAGE:string,MATCHEDDN:string,NBENTRIES:integer,ETIME:integer"
      # vds_events:
      #   enabled: true
      #   path: "/opt/radiantone/vds/vds_server/logs/vds_events.log"
      #   index: vds_events.log
      #   # custom_index:
      #   # splunk_index:
      #   # splunk_source:
      #   # splunk_sourcetype:
      # periodiccache:
      #   enabled: true
      #   path: "/opt/radiantone/vds/vds_server/logs/periodiccache.log"
      #   index: periodiccache.log
      #   # custom_index:
      #   # splunk_index:
      #   # splunk_source
      #   # splunk_sourcetype
      # web:
      #   enabled: true
      #   path: "/opt/radiantone/vds/vds_server/logs/jetty//web.log"
      #   index: web.log
      #   # custom_index:
      #   # splunk_index:
      #   # splunk_source
      #   # splunk_sourcetype
      # web_access:
      #   enabled: true
      #   path: "/opt/radiantone/vds/vds_server/logs/jetty/web_access.log"
      #   index: web_access.log
      #   # custom_index:
      #   # splunk_index:
      #   # splunk_source
      #   # splunk_sourcetype
      # sync_engine:
      #   enabled: true
      #   path: "/opt/radiantone/vds/vds_server/logs/sync_engine.log"
      #   index: sync_engine.log
      #   # custom_index:
      #   # splunk_index:
      #   # splunk_source
      #   # splunk_sourcetype
      # alerts:
      #   enabled: true
      #   path: "/opt/radiantone/vds/vds_server/logs/alerts.log"
      #   index: alerts.log
      #   # custom_index:
      #   # splunk_index:
      #   # splunk_source
      #   # splunk_sourcetype
      # adap_access:
      #   enabled: true
      #   path: "/opt/radiantone/vds/vds_server/logs/adap_access.log"
      #   index: adap_access.log
      #   # custom_index:
      #   # splunk_index:
      #   # splunk_source
      #   # splunk_sourcetype
      # admin_rest_api_access:
      #   enabled: true
      #   path: "/opt/radiantone/vds/vds_server/logs/admin_rest_api_access.log"
      #   index: admin_rest_api_access.log
      #   # custom_index:
      #   # splunk_index:
      #   # splunk_source
      #   # splunk_sourcetype
    # configFile: /fluentd/etc/fluent.conf
    aggregators:
      - type: "elasticsearch"
        host: "elasticsearch-master"
        port: "9200"
      # - type: "elasticsearch"
      #   host: "elasticsearch-master"
      #   port: "9200"
      #   scheme: "https"
      #   user: "xxxx"
      #   password: "xxxx"
      # - type: "opensearch"
      #   host: "opensearch-cluster-master"
      #   port: "9200"
      #   user: "admin"
      #   password: "admin"
      # - type: "opensearch"
      #   host: "opensearch-cluster-master"
      #   port: "9200"
      #   scheme: "https"
      #   user: "xxxx"
      #   password: "xxxx"
      # - type: "splunk_hec"
      #   hec_host: "splunk-s1-standalone-service.splunk-operator.svc.cluster.local"
      #   hec_port: "8088"
      #   hec_token: ""
      #   source: ""
      #   sourcetype: "*"
      #   insecure_ssl: "true"
        # hec_index: ""
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 5
