# AWS Configuration ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
  namespace: duploservices-rli-use2-jdh03
data:
  aws-region: "us-east-2"  # Replace with your AWS region
  # s3-bucket: "duploservices-rli-ops05-raht-r1-backups-125328463501"  # Replace with your actual S3 bucket name
  s3-bucket: "duploservices-rli-use2-jdh03-r1-backups-252604557000"
---
# State Management ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: logs-sync-state
  namespace: duploservices-rli-use2-jdh03
data:
  state.json: |
    {"first_run": true, "last_run": null, "processed_files": []}
---
# CronJob Definition
apiVersion: batch/v1
kind: CronJob
metadata:
  name: logs-to-s3-sync
  namespace: duploservices-rli-use2-jdh03
spec:
  schedule: "* * * * *"  # Run at midnight UTC
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: logs-sync-sa
          nodeSelector:
            tenantname: duploservices-rli-use2-jdh03
          containers:
          - name: logs-sync
            image: ubuntu:22.04  # Changed from amazon/aws-cli to Ubuntu
            command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Starting setup at $(date -u)"

              # Install required packages
              apt-get update
              apt-get install -y curl jq unzip

              # Install AWS CLI
              echo "Installing AWS CLI..."
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install

              # Create work directory
              mkdir -p /workspace
              cd /workspace

              # Install kubectl
              echo "Installing kubectl..."
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              mv kubectl /usr/local/bin/

              # Copy script to writable location and make executable
              cp /scripts/sync-logs-to-s3.sh /workspace/
              chmod +x /workspace/sync-logs-to-s3.sh

              # Run script
              echo "Starting sync script execution at $(date -u)"
              /workspace/sync-logs-to-s3.sh
            env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: aws-region
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: aws-config
                  key: s3-bucket
            resources:
              requests:
                cpu: "200m"
                memory: "512Mi"
              limits:
                cpu: "500m"
                memory: "1Gi"
            volumeMounts:
            - name: temp-storage
              mountPath: /tmp/logs_to_sync
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: workspace
              mountPath: /workspace
          volumes:
          - name: temp-storage
            emptyDir: {}
          - name: scripts
            configMap:
              name: sync-logs-script
              defaultMode: 0755
          - name: workspace
            emptyDir: {}
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 300
---
# Script ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-logs-script
  namespace: duploservices-rli-use2-jdh03
data:
  sync-logs-to-s3.sh: |
    [Content of your sync-logs-to-s3.sh file]
---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logs-sync-sa
  namespace: duploservices-rli-use2-jdh03
---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logs-sync-role
  namespace: duploservices-rli-use2-jdh03
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/cp"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logs-sync-rolebinding
  namespace: duploservices-rli-use2-jdh03
subjects:
- kind: ServiceAccount
  name: logs-sync-sa
  namespace: duploservices-rli-use2-jdh03
roleRef:
  kind: Role
  name: logs-sync-role
  apiGroup: rbac.authorization.k8s.io
